name: klaviyo_flutter
description: Flutter plugin for Klaviyo integration. Provides push messaging
  and Klaviyo analitics services
version: 0.1.1
homepage: https://github.com/drybnikov/klaviyo_flutter

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: 2.1.8
  equatable: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: 1.18.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rightbite.denisr
        pluginClass: KlaviyoFlutterPlugin
      ios:
        pluginClass: KlaviyoFlutterPlugin
